### ISSUE TITLE
reinforceAttack Bug

### ISSUE THREAD

**Issue by nikohd12** [coccoinomane/crabada.py#10]
Hi Cocco,

As discussed, I have tried the new reinforceAttack on my latest loot and I am getting this error.

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)

  File "/home/ec2-user/crabada-niko/bin/looting/reinforceAttack.py", line 28, in <module>
    nReinforced = reinforceAttack(userAddress)

  File "/home/ec2-user/crabada-niko/src/bot/looting/reinforceAttack.py", line 40, in reinforceAttack
    strategyName = user.getTeamConfig(mine["team_id"]).get("reinforceStrategyName")

AttributeError: 'NoneType' object has no attribute 'get'
```

I encountered this error before when running the reinforceDefense script when a team that is mining is not added to the roster of teams in the **.env** file.

With this looting wallet, I have only 1 team. So I am not sure why I am encountering this error.

Upon manual reinforcement, the script can read that the user does not need reinforcements.

`src.common.logger - INFO - No loots to reinforce for user 0x123456`

**Comment by nikojaro** [comment]
I tried manually reinforcing, do you think this could be the error?

![image](https://user-images.githubusercontent.com/8951988/158487864-b4b2e97d-aa59-406c-a2ad-669527f3da93.png)

**Comment by nikojaro** [comment]
Hi Cocco,

I was able to fix the issue by replacing `strategyName = user.getTeamConfig(mine["team_id"]).get("reinforceStrategyName")` with `strategyName = user.getTeamConfig(mine["attack_team_id"]).get("reinforceStrategyName")`

**Comment by coccoinomane** [comment]
Hey  @nikohd12 , good find! That's a subtle bug, I just pushed the change 👍

I have created a new issue concering the failed tx on reinforceAttack, please feel free to contribute > https://github.com/coccoinomane/crabada.py/issues/12

Cheers,
Cocco
