### ISSUE TITLE
could not find a suitable reinforcement

### ISSUE THREAD

**Issue by ck0111** [coccoinomane/crabada.py#106]
I'm getting Strategy 'HighestMpHighCost' could not find a suitable reinforcement for team xxxx.
HighestMp works though.

**Comment by loayei** [comment]
check your limits for price. Are you using swimmer or c-chain?

**Comment by coccoinomane** [comment]
Closing the issue.

Let us know @ck0111 if you need more help :-)

Cheers,
Cocco
