### ISSUE TITLE
No mines to reinforce for user XXX; No mines to close for user XXX;

### ISSUE THREAD

**Issue by hubbabubish** [coccoinomane/crabada.py#107]
Hey guys, thank you for your amazing work.
I've been trying to set up crabada.py for mining + reinforcement for 58 teams with 5% donations to support your work.

I've tried setting .env both with all my teams independently line by line as well as grouping them. In both scenarios they get sent to mine, but won't find any games to reinforce although they are instantly there, and neither close any of the finished mines.

```USER_1_TEAM_1="26235"
USER_1_TEAM_1_TASK="mine"
USER_1_TEAM_1_REINFORCE_STRATEGY="HighestMp"
USER_1_TEAM_1_REINFORCEMENT_TO_PICK="2"

USER_1_TEAM_2="23326"
USER_1_TEAM_2_TASK="mine"
USER_1_TEAM_2_REINFORCE_STRATEGY="HighestMp"
USER_1_TEAM_2_REINFORCEMENT_TO_PICK="2"

USER_1_TEAM_3="523526"
USER_1_TEAM_3_TASK="mine"
USER_1_TEAM_3_REINFORCE_STRATEGY="HighestMp"
USER_1_TEAM_3_REINFORCEMENT_TO_PICK="2"

USER_1_TEAM_4="236726"
USER_1_TEAM_4_TASK="mine"
USER_1_TEAM_4_REINFORCE_STRATEGY="HighestMp"
USER_1_TEAM_4_REINFORCEMENT_TO_PICK="2"```
``````
```
USER_1_GROUP_1_TEAMS="2367,1252,15242,55123,12552,56723,12566,125561"
USER_1_GROUP_1_TASK="mine"
USER_1_GROUP_1_REINFORCE_STRATEGY="HighestMp"
USER_1_GROUP_1_REINFORCEMENT_TO_PICK="2"````

```
Using Python 3.9 

The errors returned are as in the issue title `No mines to reinforce for user XXX; No mines to close for user XXX;.`  I've tested the API and I can find my mines at `https://idle-game-api.crabada.com/public/idle/mine/mineID`

Do you have any ideas what might be wrong with my setup?

**Comment by nikohd12** [comment]
Make sure that ur TEAM IDs are correct. Doesn’t look like it if ur on swimmer having team ID number 50000

**Comment by hubbabubish** [comment]
> Make sure that ur TEAM IDs are correct. Doesn’t look like it if ur on swimmer having team ID number 50000

Those are random numbers as an example, the ID's are ok. I successfully send them to mine, but they won't reinforce or close.

**Comment by nikohd12** [comment]
Ensure that you are using master and the wallet address when using the command is correct. Make sure also that ur using infinite gas on swimmer network as it is using 10000 gwei or something

**Comment by hubbabubish** [comment]
Confirming: gas is set at "inf"; I'm on latest commit `1db3d6d` on master; Address is correct;

**Comment by nikohd12** [comment]
That’s weird. Start fresh and follow the instructions correctly. Bot is working for 2 of my wallets and 1 friend’s wallet.

**Comment by hubbabubish** [comment]
Could it have something to do with the large number of teams? It's weird that mines start fine, just close and reinforce having trouble. I've followed the instructions from the wiki, is there any specific instructions I should follow?

**Comment by nikohd12** [comment]
> Could it have something to do with the large number of teams? It's weird that mines start fine, just close and reinforce having trouble. I've followed the instructions from the wiki, is there any specific instructions I should follow?

I doubt. I have 17 teams in 1 wallet.

**Comment by yigitest** [comment]
😱  54 teams

I just pushed new branch for the : https://github.com/coccoinomane/crabada.py/tree/FIX/api-for-large-number-of-teams
Can you please try the latest code from this branch and report back if the issue is solved?

**Comment by hubbabubish** [comment]
> 😱 54 teams
> 
> I just pushed new branch for the issue here: https://github.com/coccoinomane/crabada.py/tree/FIX/api-for-large-number-of-teams Can you please try the latest code from this branch and report back if the issue is solved?

Unfortunately, getting the same output. Thanks for trying to help!

**Comment by yigitest** [comment]
@hubbabubish I made one more change. Please check again.

It's hard to debug without an example, I will ask for your public key if that doesn't work either.

**Comment by hubbabubish** [comment]
> @hubbabubish I made one more change. Please check again.
> 
> It's hard to debug without an example, I will ask for your public key if that doesn't work either.

No change, here is my public address: 0xC37c3037161aed77BbDBFc36213a93d588025676

**Comment by yigitest** [comment]
@hubbabubish  oops, used max instead of min value.   
Can you please try the latest code from this branch again? Hopefully for the last time 🤞

**Comment by hubbabubish** [comment]
> @hubbabubish oops, used max instead of min value. Can you please try the latest code from this branch again? Hopefully for the last time 🤞

Issue solved, thank you so much! I'm activating the donate, cheers!

**Comment by coccoinomane** [comment]
Thank you @hubbabubish for your generous donation!
As far as I know, you are the biggest crab-whale of crabada.py 😁

... and thanks to @yigitest for the quick fix 💪
