### ISSUE TITLE
Donating not working

### ISSUE THREAD

**Issue by Mrooie** [coccoinomane/crabada.py#108]
Hi,
I've set up the newest pull request and donation is not working.

I've tried:
`DONATE_PERCENTAGE="3"
DONATE_PERCENTAGE="3%"
DONATE_PERCENTAGE=3
DONATE_PERCENTAGE=3%`

Neither works, I don't see any transactions and still sends me the donation message. :)

I'm using bot with this command:
`-m bin.mining.run` (no user address, maybe that's the case?)

**Comment by coccoinomane** [comment]
Hello @Mrooie!

Thank you so much for letting us know, appreciate it 💪

On my side, the `bin.mining.run` script works fine with donations.
Could you please check whether:

1. The folder `storage/logs/app` exists, and
2. In that folder, is there a *claims.log* file containing your last rewards?

The file should look something like this:

<img width="217" alt="Markup 2022-05-15 at 20 16 26" src="https://user-images.githubusercontent.com/3920436/168487782-306f834c-2f01-412a-9121-c3b815d0ef42.png">

Cheers,
Cocco

**Comment by Mrooie** [comment]
Hi,
No such file exists. Only app.log.

**Comment by coccoinomane** [comment]
Thanks for checking!

If you have the app.log file, then it should not be an issue with the filesystem.

Maybe it's a config parsing problem.

Could you please:

1. Pull the latest commit from `master`, and
2. run the command `python3 -m src.tests.testConfig`?

In the output you should see your donation settings, like in this example:
<img width="431" alt="Markup 2022-05-15 at 20 27 33" src="https://user-images.githubusercontent.com/3920436/168488213-1186ff65-c4b1-47d4-a7df-8f30d4bc143e.png">

Thanks!

**Comment by coccoinomane** [comment]
Now that I think about it, some commits ago, we disabled donations.

Maybe just pulling from `master` will do it 😅

**Comment by Mrooie** [comment]
Hiiiiii,
Thank you, it worked. Hurray! 🤩  
I'm kinda surprised, 'cause I did pull from master... but maybe I've messed with my folders with different branches. 😅 Thats quite probable, sorry for trouble.

**Comment by coccoinomane** [comment]
Haha, glad it worked!

No trouble at all, this kind of stuff always happens after a big update 🙂

Have a nice  day,
Cocco
