### ISSUE TITLE
Donation not work

### ISSUE THREAD

**Issue by bahrie127** [coccoinomane/crabada.py#112]
Hi Cocco,

i'm run this command : python3 -m bin.mining.closeMines {user address}
close mines is done but there is error, i think this is becouse donation, like this the log:

 transactionHash -> HexBytes('0x0f2bab25cd9487170bb989954a818dabd3889a1b330de41e65e49b7748df3563')
    transactionIndex -> 8
    type -> '0x1'
}
src.common.logger - DEBUG - Spent 1.61639 TUS
src.common.logger - INFO - Mine 210206 closed correctly
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x0f2bab25cd9487170bb989954a818dabd3889a1b330de41e65e49b7748df3563') and logIndex: 12 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.

i'm already run this command: python3 -m src.tests.testConfig
'>>> USERS & TEAMS'
[{'address': '0xFxxxxx',
  'closeLootMaxGasInGwei': inf,
  'closeMineMaxGasInGwei': inf,
  'mineMaxGasInGwei': inf,
  'reinforcementMaxGasInGwei': inf,
  'reinforcementMaxPriceInTus': 25.0,
  'reinforcementMaxPriceInTusWei': 25000000000000000000,
  'staggeringDelayInMinutes': 35,
  'staggeringGroups': [],
  'teams': [{'battlePoints': None,
             'groupNumber': 0,
             'id': xxxxx,
             'lootStrategies': ['LowestBp'],
             'reinforceStrategies': ['HighestBpHighCost'],
             'reinforcementToPick': 1,
             'task': 'mine',
             'teamNumber': 1,
             'userAddress': '0xFxxxxxx'}]}]
>>> NODE URI
https://subnets.avax.network/swimmer/mainnet/rpc
>>> DONATE PERCENT
1.0
>>> DONATE FREQUENCY
10
>>> NOTIFICATIONS
{'instantMessage': {'enable': True}}
>>> TELEGRAM

can u help me?

Thanks,

**Comment by coccoinomane** [comment]
Hello @bahrie127 and welcome to the community!

Is this the error you are referring too?

```
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/web3/contract.py:1166: UserWarning: The log with transaction hash: HexBytes('0x0f2bab25cd9487170bb989954a818dabd3889a1b330de41e65e49b7748df3563') and logIndex: 12 encountered the following error during processing: MismatchedABI(The event signature did not match the provided ABI). It has been discarded.
```

If so, it is just a warning: nothing to worry about.

Otherwise, please let us know what the error is.

Cheers,
Cocco
