### ISSUE TITLE
Reinforce strategy with own crabs

### ISSUE THREAD

**Issue by coccoinomane** [coccoinomane/crabada.py#13]
In https://github.com/coccoinomane/crabada.py/issues/12 @nikohd12 and @blanketry kindly proposed a brand new reinforce strategy:

1. If Inventory Crab is available, then reinforce with it
2. Else, reinforce using tavern with maxTus price set and strategy.

I see how such strategy would be useful to players with spare crabs, and I am happy to help anybody who wants to go ahead and implement it.

As a first step in this direction, in the next few days I am going to extend the README with a brief tutorial on how to implement a new strategy.

Cheers,
Cocco

**Comment by nikohd12** [comment]
Thank you as always, @coccoinomane 

With staggering (30-minute gap per mining team) and self-reinforce being the most efficient and optimal mining setup, this would be great!

**Comment by yigitest** [comment]
@coccoinomane  I've implemented this in a private branch and currently testing it.
I would send a PR in couple of days (need to do a cleanup first). 

A quick question: Is it ok to return list of Crabs from `.query()`? I made neccessary changes in `ReinforceStrategy` base class and other strategies.

```
def query(self, game: Game) -> List[CrabForLending]:
      """1. Checks inventory first for self/reinforceable crabs.
      2. If no crab is available, uses tavern as usual.
      """
      inventory_crabs = self.web2Client.listCrabsForLendingFromInventory(
          user_address=self.user.address
      )
      if inventory_crabs:
          return inventory_crabs

      params = {
          "limit": 100,  # TODO: make it an argument
          "orderBy": "price",
          "order": "asc",
      }
      return self.web2Client.listCrabsForLending(params)
```

**Comment by nikohd12** [comment]
@coccoinomane @yigitest

So far so good. Let me know if you need me to send the logs, but I have reinforced my own crabs for about 6 hours now.

**Comment by coccoinomane** [comment]
@nikohd12 @blanketry @laddyoh 

Hey guys,

Together with @yigitest we implemented a new mechanism to self-reinforce from inventory, with the possibility so specify a fallback strategy if there are no crabs in the inventory.

The mechanism is very simple and documented in the README [here](https://github.com/coccoinomane/crabada.py/issues/37).

I'll keep the issue open for a couple of days in case you have some feedback 🙂

Cheers,
Cocco

**Comment by coccoinomane** [comment]
Oops, wrong link.
This is where the new fallback mechanism is explained > https://github.com/coccoinomane/crabada.py#--fallback-strategies

**Comment by nikohd12** [comment]
Apologies for the delay in reply @coccoinomane.

The fallback mechanism is soo good! I also love that we can now choose if a crab is High BP or MP from the inventory. This is useful for wallets with looters and miners.

As always, @yigitest's commit on self reinforce has been a life-saver for a team of 14.

Thank you to all who contributed on making reinforce with own crabs work.

**Comment by coccoinomane** [comment]
Thanks @nikohd12 for your feedback!

I assume no bugs so far with the fallback mechanism? 🤞

**Comment by coccoinomane** [comment]
Great to know 🙂

Closing the issue.
