### ISSUE TITLE
reinforceDefense bug when there is a team not included in .env

### ISSUE THREAD

**Issue by nikohd12** [coccoinomane/crabada.py#15]
Hi @coccoinomane,

I have encountered this error when trying to run reinforceDefense on a wallet with an auto-lose team (not enrolled in .env because we are auto-losing this team)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/crabada-pool/bin/mining/reinforceDefense.py", line 28, in <module>
    nReinforced = reinforceDefense(userAddress)
  File "/home/ec2-user/crabada-pool/src/bot/mining/reinforceDefense.py", line 42, in reinforceDefense
    strategyName = user.getTeamConfig(mine["team_id"]).get("reinforceStrategyName")
```

Basically, let's say you have 3 teams. 2 high mp crabs and 1 Bulk Bulk Bulk.

You would rather auto lose BBB vs. reinforcing them for +EV return.

**Comment by EugeneTeu** [comment]
its failing because the `teamConfig` is None. maybe u could pass in a default value there or add an if statemnt when u trying to get the strategy

**Comment by nikohd12** [comment]
What do you suggest? Would passing a default value be more friendly for everyone? or an if statement?

**Comment by EugeneTeu** [comment]
likely could create a new strategy that returns no crabs, then register that crab team under `.env` with that strategy name

**Comment by nikohd12** [comment]
> likely could create a new strategy that returns no crabs, then register that crab team under `.env` with that strategy name

Or a blacklist of teams for no reinforce, but can mine and settle.

**Comment by nikohd12** [comment]
Do you have an idea for a NoReinforce strategy logic? @EugeneTeu

**Comment by EugeneTeu** [comment]
```python

class NoReinforceStrategy(ReinforceStrategy):
   
  def crab(self, game: Game, list: List[CrabForLending]) -> CrabForLending:
   return None 

```

@coccoinomane

**Comment by nikohd12** [comment]
Thank you @coccoinomane, I guess that fixed the bug I reported.

**Comment by coccoinomane** [comment]
Thanks @nikohd12 for spotting this bug, and thanks @EugeneTeu for proposing the new strategy 👍

The bug is actually worse than what it seems, because the bot should not consider a team unless it is not explcitly listed in *.env*. I have fixed this part in https://github.com/coccoinomane/crabada.py/pull/18

I also pushed the NoReinforceStrategy.py to `master` (https://github.com/coccoinomane/crabada.py/commit/398a9ce48bc077f5fe05868d6372c92c2a49c191).
@EugeneTeu I slightly changed your approach and overridden the `query` method rather than the `getCrab` method in order to avoid making a useless query to Crabada.

@nikohd12 , would you mind testing if the `NoReinforce` strategy fixes the original bug?

Thanks,
Cocco

**Comment by nikohd12** [comment]
> Thanks @nikohd12 for spotting this bug, and thanks @EugeneTeu for proposing the new strategy 👍
> 
> The bug is actually worse than what it seems, because the bot should not consider a team unless it is not explcitly listed in _.env_. I have fixed this part in #18
> 
> I also pushed the NoReinforceStrategy.py to `master` ([398a9ce](https://github.com/coccoinomane/crabada.py/commit/398a9ce48bc077f5fe05868d6372c92c2a49c191)). @EugeneTeu I slightly changed your approach and overridden the `query` method rather than the `getCrab` method in order to avoid making a useless query to Crabada.
> 
> @nikohd12 , would you mind testing if the `NoReinforce` strategy fixes the original bug?
> 
> Thanks, Cocco

Will do, I'll have to wait for my auto-lose team to finish and add them to my .env with NoReinforce. I'll update once testing is done.

Thank you!

**Comment by coccoinomane** [comment]
Take your time, no worries 🙂

**Comment by nikohd12** [comment]
Hi @coccoinomane,

My auto-lose team kept on losing. Your commit worked! Thank you! No more errors upon checking cron mail too.

**Comment by coccoinomane** [comment]
I am sorry for the team's morale, but happy for the bot ;-)
Thank you for letting me know, I am closing the issue.
Cheers,
Cocco
