### ISSUE TITLE
hi, i don't understand how to run the software. can you help me?

### ISSUE THREAD

**Issue by nurullahk5656** [coccoinomane/crabada.py#2]

**Comment by coccoinomane** [comment]
Hey @nurullahk5656 , I have improved the readme, let me know if it is clearer for you now :-)

**Comment by nurullahk5656** [comment]
hello sir. I don't have much coding knowledge. and I work a busy 12-hour job. If you have a lot but, I want to buy it. Can you help me? Thank you

iPhone’umdan gönderildi

**Comment by nikohd12** [comment]
> 

I can help you set it up when I am free. Are you familiar with AWS?

**Comment by nurullahk5656** [comment]
No, I'm not familiar with it. But if I need to look, I can look up what it is from a source.

iPhone’umdan gönderildi

> GeekFromPH ***@***.***> şunları yazdı (23 Mar 2022 11:27):
> 
> I can help you set it up when I am free. Are you familiar with AWS?

**Comment by nurullahk5656** [comment]
Hello sir. I don't have much coding knowledge. and I work a busy 12-hour job. If you have a looting bot I would like to buy it. Can you help me? Thank you

iPhone’umdan gönderildi
