### ISSUE TITLE
No loots to reinforce for user

### ISSUE THREAD

**Issue by loayei** [coccoinomane/crabada.py#20]
For some reason in my end I keep getting that there are not any loots to reinforce even though I do have some. 
Not sure If I am doing something wrong. For the USER_TASK do I have to change it to loot from mine?

**Comment by nikohd12** [comment]
Yes, you have to assign tasks for teams, @loayei

**Comment by loayei** [comment]
I did assign loot but still getting the same issue. @nikohd12 I created a figment API app and added avalanche network as well. included my public and private keys. Still no luck. :(. 
Would appreciate help

**Comment by nikohd12** [comment]
> I did assign loot but still getting the same issue. @nikohd12 I created a figment API app and added avalanche network as well. included my public and private keys. Still no luck. :(. Would appreciate help

Make sure you are using reinforceAttack, your team has "loot" as its assignment and a Reinforce Strategy. Can you please paste the logs here too.

**Comment by loayei** [comment]
2022-03-23 01:02:48,126 - src.common.logger - INFO - No loots to reinforce for user 0x5daD7ac5922

all logs are practically the same as above.
This is the message am getting when I use 

python -m bin.looting.reinforceAttack 0x5daD7a

I tried with windows as well as MAC same issue.
so it must be something I am doing wrong

**Comment by nikohd12** [comment]
Make sure the address you are using is correct, my auto reinforce for looting is working perfectly fine.

Can you try downgrading to a lower version? [Try this branch](https://github.com/coccoinomane/crabada.py/tree/2022-03-20_test_higher_reinforce_bid), follow the .env.example there.

**Comment by loayei** [comment]
It worked!!!

**Comment by nikohd12** [comment]
> It worked!!!

@coccoinomane, there might be an issue from the latest commit. I haven't tried the n-th implementation yet, I am still using [this branch](https://github.com/coccoinomane/crabada.py/tree/2022-03-20_test_higher_reinforce_bid) for my looting teams.

**Comment by loayei** [comment]
@nikohd12 Really appreciate all the help!!

**Comment by coccoinomane** [comment]
Thanks guys for discussing this, and @nikohd12 for providing a quick fix for @loayei 
I am looking into the issue, see https://github.com/coccoinomane/crabada.py/issues/24
