### ISSUE TITLE
Figment API key error

### ISSUE THREAD

**Issue by nomercy1337** [coccoinomane/crabada.py#21]
Getting the following error when running the mine script: 

File "C:\Users\Maste\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://avalanche--mainnet--rpc.datahub.figment.io/apikey/%3CYOUR%20FIGMENT%20API%20KEY%3E/ext/bc/C/rpc

I got myself an API key from figment datahub. Where do I need to insert the variable?

**Comment by loayei** [comment]
Where it says Your figment API Key. Replace that with your API key! @nomercy1337

**Comment by nomercy1337** [comment]
> Where it says Your figment API Key. Replace that with your API key! @nomercy1337

Looked through all the python files but can't seem to find the variable anywhere. You got an idea where it might be located?

**Comment by loayei** [comment]
its on the .env file.

**Comment by nomercy1337** [comment]
Wauw, not sure how I could have missed that. Cheers!
