### ISSUE TITLE
CronJob issue

### ISSUE THREAD

**Issue by loayei** [coccoinomane/crabada.py#22]
When I start a cron job It is giving me this error in the mail .. 
`
/opt/homebrew/opt/python@3.9/bin/python3.9: Error while finding module specification for 'bin.looting.reinforceAttack' (ModuleNotFoundError: No module named 'bin')
`

@nikohd12

**Comment by loayei** [comment]
It works all fine in the terminal. But having issues with the cron job 
This is what I input on the crontab 
`*/2 * * * * cd '/Users/loayei/Documents/RealChromeVersion/crabada.py' && '/usr/local/bin/python3' -m bin.looting.reinforceAttack 0xFA3B35cbAC
`

**Comment by loayei** [comment]
Quick update this was solved by giving Full Disk Access for cron.

**Comment by nikohd12** [comment]
You may close this issue @loayei. This is an operating system related issue.

**Comment by loayei** [comment]
True my bad
