### ISSUE TITLE
No loots to reinforce

### ISSUE THREAD

**Issue by loayei** [coccoinomane/crabada.py#24]
The new implementation of the nth strategy broke the program on my end. 
It says there are no loots to reinforce. Previous versions are working fine.

Is it working on anyone's end?

**Comment by coccoinomane** [comment]
Thanks @loayei for reporting the issue: I will look at it in the next 24hr.
In the meanwhile it would be great if other players could provide feedback on whether they experience the same issue.
Cheers,
Cocco

**Comment by nikohd12** [comment]
Thank you as always @coccoinomane

**Comment by loayei** [comment]
> Thanks @loayei for reporting the issue: I will look at it in the next 24hr. In the meanwhile it would be great if other players could provide feedback on whether they experience the same issue. Cheers, Cocco

Thanks for getting back to us! Appreciate it..

**Comment by loayei** [comment]
In another update, I tried closing mines I am getting the same issue. I believe it has to do with pulling my team's data. I could be wrong tho

**Comment by coccoinomane** [comment]
@loayei 

I have found a bug in an helper function `fetchOpenLoots` and fixed it in [the lastest commit to master](https://github.com/coccoinomane/crabada.py/commit/0d4b884ae475cf86be1279f3457e853b80f6df0f).

Could you please try reinforcing your loots again? It should work now.

**Comment by coccoinomane** [comment]
Great, thanks for the quick feedback 💪

I will close the issue; feel free to reopen it if you encounter further issues.

Cheers,
Cocco

**Comment by loayei** [comment]
@coccoinomane Hey I think this fix broke the sendTeamsMining.
Now it says no teams available to send mining

**Comment by coccoinomane** [comment]
Hey @loayei , could you please do some more debug on your end?

Sending teams works fine for me, I ran it all night.

**Comment by loayei** [comment]
oh my bad. Didn't change the task
