### ISSUE TITLE
No loot to be found when doing reinforce attack

### ISSUE THREAD

**Issue by ck0111** [coccoinomane/crabada.py#25]
Hello, 

I encountered "No loot to reinforce for user" when trying to do reinforce attack

**Comment by coccoinomane** [comment]
Hi @ck0111 , thank you for the report!
I see you have closed the issue, I assume you fixed your problem?
PS: If not, please try the latest commit on master.

**Comment by ulgacemre** [comment]
Yes, I also take this error and updating solve the problem for me. @coccoinomane @ck0111
