### ISSUE TITLE
Raspberry PI

### ISSUE THREAD

**Issue by loayei** [coccoinomane/crabada.py#28]
I am trying to run the scripts but I am facing dotenv module not found.
Anybody knows how to fix this?

I am testing using a raspberry pi.

**Comment by ulgacemre** [comment]
"python -m pip install python-dotenv" you can try this one.

**Comment by loayei** [comment]
Yeah i tried everything with raspberry pi. It doesn't seem to work on Raspian and Ubuntu is too heavy on it. I will close this issue.

**Comment by coccoinomane** [comment]
Sorry for that @loayei , I am not sure how to help you as I have never used a Raspberry.

If it can help, I run the bot on [a Debian machine on Vultr](https://www.vultr.com/), it only costs $6 a month and it never game me problems.

**Comment by loayei** [comment]
That's exactly what am looking for. I will try it out now. Does it have a GUI interface or is it like Ubuntu Server? 
@coccoinomane

**Comment by coccoinomane** [comment]
No GUI, you need to SSH into it.
Just make sure to install python > `apt-get install python3 pip git`
Then just follow the README :-)

**Comment by coccoinomane** [comment]
(I prefer to use the Terminal, but Vultr also allows you to SSH directly via their website)

<img width="1301" alt="Markup 2022-03-30 at 06 47 55" src="https://user-images.githubusercontent.com/3920436/160753483-c663ba09-0b5e-47f5-8349-d58e453ce315.png">

**Comment by loayei** [comment]
@coccoinomane Thanks alot I will try it now and see how it goes.

**Comment by loayei** [comment]
@coccoinomane I was able to install a GUI successfully on Vultr If you want me to add instructions to the ReadME file or something I can as soon as I successfully run the bot on it.

**Comment by loayei** [comment]
Its working just let me know if you need me to add it.

**Comment by coccoinomane** [comment]
That's great @loayei , I am happy you managed 💪

A short tutorial would be great.
Do you feel like creating a Wiki page?
You should be able to create one here > https://github.com/coccoinomane/crabada.py/wiki

**Comment by loayei** [comment]
> That's great @loayei , I am happy you managed 💪
> 
> 
> 
> A short tutorial would be great.
> 
> Do you feel like creating a Wiki page?
> 
> You should be able to create one here > https://github.com/coccoinomane/crabada.py/wiki
> 
> 
> 
> 
> 
> 

Yeah I can do that. I'll try to post it by tomorrow.
