### ISSUE TITLE
No mines to reinforce for user ......

### ISSUE THREAD

**Issue by ulgacemre** [coccoinomane/crabada.py#29]
Is there any solution for "No mines to reinforce for user" ?

**Comment by nikohd12** [comment]
@ulgacemre your team is not enrolled. Please check the README section.

**Comment by nikohd12** [comment]
This isn't a bug.

**Comment by coccoinomane** [comment]
Hi @ulgacemre , and welcome to the community!

As Niko suggested, you need to explicitly you teams in _.env_. Are you mining or looting?

Let us know if you solve your issue :-)

**Comment by ulgacemre** [comment]
@nikohd12 @coccoinomane thanks for warm welcome pleasure to be here.

In fact I added 2 teams and mine and closing mine are working well. 

But when I try to do reinforcement it gives that error "No mines to reinforce for user"  so that it did not make any defense for the attack. That's the case. 

# =========
# = TEAMS =
# =========
USER_1_TEAM_1="235XX"
USER_1_TEAM_1_REINFORCE_STRATEGY="HighestBp" # look in ReinforceStrategyFactory.py for available strategies
USER_1_TEAM_1_TASK="mine"
USER_1_TEAM_1_REINFORCEMENT_TO_PICK="1" # increase to avoid failed tx at a potential expense of stats value


USER_1_TEAM_2="235XX"
USER_1_TEAM_2_REINFORCE_STRATEGY="HighestBp" # look in ReinforceStrategyFactory.py for available strategies
USER_1_TEAM_2_TASK="mine"
USER_1_TEAM_2_REINFORCEMENT_TO_PICK="1" # increase to avoid failed tx at a potential expense of stats value

**Comment by ulgacemre** [comment]
@coccoinomane @nikohd12  what do you think about the error?

**Comment by coccoinomane** [comment]
Hi @ulgacemre ,

I am using the exact same configuration, but it works fine on my side.

I am not sure what the issue could be... are you sure you are on the latest commit of master?

**Comment by ulgacemre** [comment]
Hi @coccoinomane @nikohd12 ,

Thanks for your responses. I upgrade the latest commit and it solved the problem.

You can close the issue.
