### ISSUE TITLE
Reinforcement to Pick

### ISSUE THREAD

**Issue by loayei** [coccoinomane/crabada.py#34]
I just wanted to note that this is very prone to failing loot reinforcing since it borrows less than pure bulks when the value is set over 1.
and 1 puts us in square one of continuous failure
@coccoinomane 
Maybe add a minimum battle point?

**Comment by loayei** [comment]
@nikohd12 I will test out this method today. and ill report back

**Comment by loayei** [comment]
Yeah its still borrowing 225 BP crabs. @nikohd12

**Comment by nikohd12** [comment]
> Yeah its still borrowing 225 BP crabs. @nikohd12

That's probably because there are no Bulks in the tavern. Nonetheless, I do think it's still fine as a looter.

**Comment by loayei** [comment]
There are plenty of Bulks in the tavern am not sure where the issue is. But would it be possible to modify the code to borrow the nth crab based on price only without changing the specs of the crab?

**Comment by loayei** [comment]
Even when reinforcement to pick is set to = "1". It still would not choose the highest BP crab all the time. I am checking on the UI of the crabada and there are plenty within the maxPrice I input.

**Comment by coccoinomane** [comment]
Hello @loayei , thank you for your report!

I have checked and failed to reproduce the issue.

Plese try to follow these steps:

1. Make sure you are on the latest commit of `master`.
2. Make sure you are on the `HighestBp` startegy.
3. Run the following command:
    ```bash
    python3 -m src.tests.strategies.reinforce.testMakeReinforceStrategy 25 1
    ```

The command will show you the highest-BP crab in the Tavern under 25 TUS. About 90% of the times  I run the command, I get a crab with 237 BP, see below screenshot.

<img width="1536" alt="Markup 2022-04-02 at 10 24 59" src="https://user-images.githubusercontent.com/3920436/161374447-11b1f9d6-ff8b-4ad1-aac0-6dd270a1f629.png">

If you vary the second parameter from 1 to 4, then you will sometime see crabs with 225 BP, because you are choosing  crabs farther below.

Cheers,
Cocco

**Comment by loayei** [comment]
I will try it now. 
If you don't mind me asking isn't getting a list of crabs sorted by bp and then price low to high is a better way. 
Then choosing the 5 or 6th crab from that list? 
rather than losing stats which can lead to a loss
@coccoinomane

**Comment by coccoinomane** [comment]
@loayei 

>If you don't mind me asking isn't getting a list of crabs sorted by bp and then price low to high is a better way.

This is exactly how we are doing it now. The strategy is very simple, please go have a look at src/strategies/reinforce/HighestBpReinforceStrategy.py and play with the parameters.

**Comment by loayei** [comment]
@coccoinomane So i was playing around with the testing. As I am choosing reinforcement to pick as soon as I pass 4 stats go down as we mentioned before. But on the UI end on crabada there is over 8 pages of pure bulks. 
Sorry for asking to much am just trying to understand why reinforcementToPick would skip all those pages. 
I am leaving my maxTUS as 30 for testing so I don't think the price is the issue.

**Comment by loayei** [comment]
@coccoinomane not sure what is happening.
But I hard coded self,maxPrice1 and am getting far better consistent results although they are pure gems. but def better than a chance of 220 bp.
Tried it with pick value up to 22 and still getting the pure gems

**Comment by coccoinomane** [comment]
After a chat with @coinmasterlisting, which I thank, I pushed a new strategy which could be what you need, @loayei .

Please checkout https://github.com/coccoinomane/crabada.py/tree/2022-04-02_high-cost-reinforce-strategy and let me know if it works for you 🙂

**Comment by loayei** [comment]
@coccoinomane Thanks a lot!
Exactly what I needed. getting 237 Bp all the time now even with pick up to 30. 
👯 👯‍♂️

**Comment by loayei** [comment]
This strategy can in other words not need the delay since you can specify each team with a different pick and still guarantee the full 237 Bp. Great work again!

**Comment by coccoinomane** [comment]
Thanks for the feedback @loayei ! 

Good to know about this interesting side effect of REINFORCEMENT_TO_PICK 💪
