### ISSUE TITLE
how to get ABI code from contract address 0x82a85407BD612f52577909F4A58bfC6873f14DA8

### ISSUE THREAD

**Issue by Mrfranken** [coccoinomane/crabada.py#45]
hi, Sir. Sorry to ask you for help by this way. If you could, could you help me with my questions? many thx
I noticed there is only bytecodes in crabada contrant, how did u translate them to ABI codes? thx again

**Comment by coccoinomane** [comment]
Hi @Mrfranken !
You can extract the ABI inspecting the JS files loaded by the play.crabada.com website, using the source tab of the browser dev tools.
... or you can just look in the contracts folder of my bot ;-)
Cheers,
Cocco
