### ISSUE TITLE
Separate gas parameter for the second reinforcement

### ISSUE THREAD

**Issue by mertf** [coccoinomane/crabada.py#47]
The suggestion is that if the mine was able to be reinforced after the first attack, issue the second reinforcement based on a separate gas parameter.

**Comment by ck0111** [comment]
Good suggestion.

**Comment by nikohd12** [comment]
This is a good suggestion! @mertf Do you think it would be better if we just increment the gas limit for the first reinforcement limit to something like +10 or +15 gwei?

With Swimmer Network nearby, we won't be needing gas limits soon.

**Comment by mertf** [comment]
> This is a good suggestion! @mertf Do you think it would be better if we just increment the gas limit for the first reinforcement limit to something like +10 or +15 gwei?
> 
> With Swimmer Network nearby, we won't be needing gas limits soon.

I believe the incrementation could just do it. But you are very right, there won't be any gas concerns soon. So maybe it might be best to utilize everyone's focus on other priorities for the bot?

**Comment by coccoinomane** [comment]
@CBSInvest Gwei is the same as nAVAX on Avalanche.

**Comment by nikohd12** [comment]
@mertf I think we can close the issue now that we’re on Swimmer already.
