### ISSUE TITLE
Separate max gas setting for looting and mining

### ISSUE THREAD

**Issue by ck0111** [coccoinomane/crabada.py#50]
When i loot i need to always reinforce no matter the gas, so it'd be nice if there is a separate gas parameter for "loot" and "mine"

**Comment by nikohd12** [comment]
> When i loot i need to always reinforce no matter the gas, so it'd be nice if there is a separate gas parameter for "loot" and "mine"

You can use a different .env file or create a folder for looting and a separate folder for mining. Run a crontab on both. :)

**Comment by coccoinomane** [comment]
Hi @ck0111 , and thanks for the suggestion.

As @nikohd12 suggests, having separate env files or bot folder would help you.

However, I would prefer to have a native solution in the bot.

Would moving the max gas setting to the team-level help solving your issue?

Cheers,
Cocco

**Comment by doru15** [comment]
Hi, i think that would be the best option to have the max gas setting on team level.
I often use one team daytime to loot (while i'm at PC) and on night time or weekend i let it mine. I change the .env file each time when i do the "switch".

**Comment by ck0111** [comment]
> Hi @ck0111 , and thanks for the suggestion.
> 
> As @nikohd12 suggests, having separate env files or bot folders would help you.
> 
> However, I would prefer to have a native solution implemented in the bot.
> 
> Would moving the max gas setting to the team-level help solving your issue?
> 
> Cheers, Cocco

Hi Coco, I think yes, moving the gas setting to team level would actually solve my issue completely. That's because I run both mining and looting teams simultaneously. It would it the best if that is possible!

**Comment by nikohd12** [comment]
> > Hi @ck0111 , and thanks for the suggestion.
> > As @nikohd12 suggests, having separate env files or bot folders would help you.
> > However, I would prefer to have a native solution implemented in the bot.
> > Would moving the max gas setting to the team-level help solving your issue?
> > Cheers, Cocco
> 
> Hi Coco, I think yes, moving the gas setting to team level would actually solve my issue completely. That's because I run both mining and looting teams simultaneously. It would it the best if that is possible!

Making gas limits on a team level would just make the **.env files** a lot more uglier. I have 10 teams all mining and the .env file looks ugly. If you want to scale, it would be better to use the [Group Functionality](https://github.com/coccoinomane/crabada.py/issues/56) idea or just have a separate folder.

cc: @coccoinomane

**Comment by nikohd12** [comment]
To add, imagine having 5 or more teams, and you have to set the following:
1. Goal (mine or loot)
2. Gas Limit (for each team)
3. Reinforcement to pick (for each team)
4. Reinforce strategy (for each team)

That would be 5 * 4 per team and the .env will look messy if you try to manage via vim.

**Comment by coccoinomane** [comment]
This is a good point @nikohd12 but, given that the team grouping solution is still on the table, I think there's an easier solution.

I was thinking of leaving the current global gas setting as a fallback, so that you need to specify the team-specific setting only for the teams that require a separate treatment.

Would that work for you?

Cheers,
Cocco

**Comment by nikohd12** [comment]
Looks good @coccoinomane. Thank you as always!

**Comment by ck0111** [comment]
> This is a good point @nikohd12 but, provided that the team grouping feature is still on the table, I think there's an easier solution for this specific need.
> 
> I was thinking of leaving the current global gas setting as a fallback, so that you need to specify the team-specific setting only for the teams that require a separate treatment.
> 
> Would that work for you?
> 
> Cheers, Cocco

@coccoinomane I saw the new team grouping, great work. However, will group specific gas limits be available in the future?

**Comment by coccoinomane** [comment]
Hi @ck0111 ,

If nobody else steps up to implement the feature, I plan to implement it after [team staggering](https://github.com/coccoinomane/crabada.py/pull/77).

Cheers,
Cocco

**Comment by nikohd12** [comment]
Hi @coccoinomane ,

I think we can close this issue now that we’re on Swimmer, will help clean up the Issues page too for u guys.

**Comment by coccoinomane** [comment]
Thank you @nikohd12 for the suggestion!

Sorry @ck0111 for not implementing this feature in the end, but with Swimmer coming it would have been very short lived.

Cheers,
Cocco
