### ISSUE TITLE
webserver .env file

### ISSUE THREAD

**Issue by loayei** [coccoinomane/crabada.py#51]
Maybe add the command to change it to private ( chmod -R 700 crabada.py)

**Comment by loayei** [comment]
Will close this issue It was just a suggestion for webservers safety.

**Comment by coccoinomane** [comment]
Thanks @loayei ,

Your issue went under my radar... I have added the suggestion in the README, together with the recommendation to NOT run the bot on a webserver at all  :-)

Cheers,
Cocco
