### ISSUE TITLE
reinforcing multiple teams doesn't revert the execution

### ISSUE THREAD

**Issue by laddyoh** [coccoinomane/crabada.py#53]
When there is only 1 team in the list to reinforce and the crab is locked, the transaction gets reverted correctly. When there are multiple teams, the transaction for the later teams fail.

src.common.logger - INFO - Strategy 'HighestBpFromInventory' could not find a suitable reinforcement for team 20710
src.common.logger - INFO - Borrowing crab 65642 for mine 4247143 at 16.5 TUS... [BP=237, MP=66]
src.common.logger - WARNING - Error reinforcing loot 4247143: execution reverted: GAME:CRAB LOCKED

src.common.logger - INFO - Strategy 'HighestBpFromInventory' could not find a suitable reinforcement for team 10104
src.common.logger - INFO - Borrowing crab 68117 for mine 4246573 at 16.8 TUS... [BP=237, MP=66]
src.common.txLogger - DEBUG - Spent 0.004207502771604567 ETH
src.common.logger - ERROR - Error reinforcing loot 4246573

**Comment by laddyoh** [comment]
I just tried again to only reinforce one team and got that same error, so it seems to not be related to multiple teams.

**Comment by coccoinomane** [comment]
Thank you @laddyoh for the report!

May I ask why you closed the issue? Did you solve it?

Thanks,
Cocco
