### ISSUE TITLE
Skip locked crabs: execution reverted: GAME:CRAB LOCKED

### ISSUE THREAD

**Issue by theBlackEndDev** [coccoinomane/crabada.py#59]
When you have many teams and a reinforcement returns "execution reverted: GAME:CRAB LOCKED" the same crab will be attempted to be used until that crab is actually pulled from the store.  My thoughts were that maybe we either wait 10-15 secs before the next team is tried or count up to the next crab.  So if REINFORCEMENT_TO_PICK="5" then we use crab 6.  Not sure if its feasible but I'll give it a look.

**Comment by nikohd12** [comment]
> When you have many teams and a reinforcement returns "execution reverted: GAME:CRAB LOCKED" the same crab will be attempted to be used until that crab is actually pulled from the store. My thoughts were that maybe we either wait 10-15 secs before the next team is tried or count up to the next crab. So if REINFORCEMENT_TO_PICK="5" then we use crab 6. Not sure if its feasible but I'll give it a look.

You can use the Reinforce Delay function :)

**Comment by coccoinomane** [comment]
Thanks @theBlackEndDev for the bug report!

As @nikohd12 pointed out, using the `REINFORCE_DELAY_IN_SECONDS` setting is the way to go.

However, the setting was not respected when the execution reverts.

I have fixed the bug it in the latest commit, could you please check whether it works for you?

**Comment by theBlackEndDev** [comment]
> 

Fix verified

**Comment by coccoinomane** [comment]
Thanks @theBlackEndDev for the feedback 💪
