### ISSUE TITLE
Reinforce Issue for more than one team

### ISSUE THREAD

**Issue by rmznovali** [coccoinomane/crabada.py#6]
When the bot finds two or more teams to reinforce, based on the reinforce rule, it finds the same crab for all teams and hires only one because the crab for the other teams is locked and gets an error. This is obviously for manual runs. With cron job, it can try again and again or the teams should be sent to mine in different times. 

Also, is there any way to import an environment file in the command line when running the bot?

**Comment by coccoinomane** [comment]
Hi @rmznovali and thanks for the bug report!
I will have a go at fixing it  next week, unless you want to try first :-)

As for the environment file, loading a custom one should be as easy as sourcing it from the terminal `source envfile && python ...`. If you have issues with comments in the env file, please check these fancy ways to import env files > https://gist.github.com/mihow/9c7f559807069a03e302605691f85572

Cheers,
Cocco

**Comment by coccoinomane** [comment]
Hello @rmznovali !

I tried ti fix the bug in the branch https://github.com/coccoinomane/crabada.py/tree/2022-03-14_reinforce_delay

Could you please let me know if it works for you?

I just introduced a delay of 30 seconds between each reinforcement attempt.

Cheers,
Cocco

**Comment by coccoinomane** [comment]
Merged.
