### ISSUE TITLE
No suitable reinforcements (HighBPStrat)

### ISSUE THREAD

**Issue by flazewang** [coccoinomane/crabada.py#61]
Hi,

Getting a lot of no suitable reinforcements error (tried various Max reinforce parameters) after Crabada got DDOS attacked. Maybe a change in API address?

Thanks.

**Comment by EugeneTeu** [comment]
switch limit to 100. Crabada team reduce the limit number

**Comment by EugeneTeu** [comment]
switch limit to 100. Crabada team reduce the limit number

**Comment by coccoinomane** [comment]
Fixed in https://github.com/coccoinomane/crabada.py/pull/65, thanks for the report!

(Also see https://github.com/coccoinomane/crabada.py/issues/64).
