### ISSUE TITLE
JSONDecodeError on attempt to reinforce 

### ISSUE THREAD

**Issue by danvaneijck** [coccoinomane/crabada.py#63]
openGames = makeCrabadaWeb2Client().listMines()
is producing 
json.decoder.JSONDecodeError

am i just getting rate limited ? cron is set to the suggested 2,12,22,32,42,52 * * * *

**Comment by coccoinomane** [comment]
Fixed in https://github.com/coccoinomane/crabada.py/pull/65, thanks for the report!

(Also see https://github.com/coccoinomane/crabada.py/issues/64).
