### ISSUE TITLE
getting JSONDecodeError on input on t rying to sendTeamsMining

### ISSUE THREAD

**Issue by 0xbitpirate** [coccoinomane/crabada.py#64]
Trying to sendTeamsMining, but getting an error. I understand that it has to do something with the API, I've rechecked that I provided the correct API key, but got no clue what's wrong.

Would appreciate any help on getting this to work.

```sh
python -m bin.mining.sendTeamsMining 0xaddress
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/a/crabada/crabada.py/bin/mining/sendTeamsMining.py", line 25, in <module>
    nSent = sendTeamsMining(User(userAddress))
  File "/home/a/crabada/crabada.py/src/bot/mining/sendTeamsMining.py", line 21, in sendTeamsMining
    availableTeams = fetchAvailableTeamsForTask(user, "mine")
  File "/home/a/crabada/crabada.py/src/helpers/teams.py", line 21, in fetchAvailableTeamsForTask
    availableTeams = makeCrabadaWeb2Client().listTeams(
  File "/home/a/crabada/crabada.py/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 114, in listTeams
    res = self.listTeams_Raw(userAddress, params)
  File "/home/a/crabada/crabada.py/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 137, in listTeams_Raw
    return requests.request("GET", url, params=actualParams).json()
  File "/home/a/.local/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by laddyoh** [comment]
I'm getting the same error

**Comment by danvaneijck** [comment]
getting the same on attempt to reinforce

**Comment by loayei** [comment]
Yeah i think its because if the late DDoS attack that happened they are limiting API requests or something.

**Comment by EugeneTeu** [comment]
add a `header` dict to the request: 

```python
headers = {
    'authority': 'idle-api.crabada.com',
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
    'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJfYWRkcmVzcyI6IjB4MTQxMTZjOTBiYTJhNzNlNzg4ZjVhNjZiMWY1YzU1NmQ3OWZlYzY5MyIsImVtYWlsX2FkZHJlc3MiOiJob2VzYmVob2VzNjdAZ21haWwuY29tIiwiZnVsbF9uYW1lIjoiQ3JhYmFkaWFuIDRiZjY1MDJiZmI2MiIsInVzZXJuYW1lIjpudWxsLCJmaXJzdF9uYW1lIjpudWxsLCJsYXN0X25hbWUiOm51bGx9LCJpYXQiOjE2NTAzMjgxMzgsImV4cCI6MTY1MjkyMDEzOCwiaXNzIjoiMjM5NTA5NTM4MWFhMjBhZWRkYjFlNWQ2MWQzOGNkZWUifQ.NIpFMW7tDOxQPY_uzqJL6BEvNHbUxKLWhrsxn7z_n8Q',
    'cache-control': 'no-cache',
    'origin': 'https://play.crabada.com',
    'pragma': 'no-cache',
    'referer': 'https://play.crabada.com/',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'sec-gpc': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Safari/537.36',
}

response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
```

**Comment by EugeneTeu** [comment]
add a `header` dict to the request: 

```python
headers = {
    'authority': 'idle-api.crabada.com',
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8',
    'authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJfYWRkcmVzcyI6IjB4MTQxMTZjOTBiYTJhNzNlNzg4ZjVhNjZiMWY1YzU1NmQ3OWZlYzY5MyIsImVtYWlsX2FkZHJlc3MiOiJob2VzYmVob2VzNjdAZ21haWwuY29tIiwiZnVsbF9uYW1lIjoiQ3JhYmFkaWFuIDRiZjY1MDJiZmI2MiIsInVzZXJuYW1lIjpudWxsLCJmaXJzdF9uYW1lIjpudWxsLCJsYXN0X25hbWUiOm51bGx9LCJpYXQiOjE2NTAzMjgxMzgsImV4cCI6MTY1MjkyMDEzOCwiaXNzIjoiMjM5NTA5NTM4MWFhMjBhZWRkYjFlNWQ2MWQzOGNkZWUifQ.NIpFMW7tDOxQPY_uzqJL6BEvNHbUxKLWhrsxn7z_n8Q',
    'cache-control': 'no-cache',
    'origin': 'https://play.crabada.com',
    'pragma': 'no-cache',
    'referer': 'https://play.crabada.com/',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'sec-gpc': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Safari/537.36',
}

response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
```

**Comment by kraussian** [comment]
Awesome, @EugeneTeu. It works now after adding those headers to `src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py`

**Comment by mertf** [comment]
@kraussian @EugeneTeu 

I have added the headers but I am getting this error after running the code to close mines.  

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/bin/mining/closeMines.py", line 13, in <module>
    from src.bot.mining.closeMines import closeMines
  File "/src/bot/mining/closeMines.py", line 9, in <module>
    from src.common.clients import makeCrabadaWeb3Client
  File "/src/common/clients.py", line 8, in <module>
    from src.libs.CrabadaWeb2Client.CrabadaWeb2Client import CrabadaWeb2Client
  File "/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 223, in <module>
    response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
NameError: name 'params' is not defined`

**Comment by EugeneTeu** [comment]
> 



> @kraussian @EugeneTeu
> 
> I have added the headers but I am getting this error after running the code to close mines. I am probably doing something wrong when adding those headers.
> 
> ```
>   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/bin/mining/closeMines.py", line 13, in <module>
>     from src.bot.mining.closeMines import closeMines
>   File "/src/bot/mining/closeMines.py", line 9, in <module>
>     from src.common.clients import makeCrabadaWeb3Client
>   File "/src/common/clients.py", line 8, in <module>
>     from src.libs.CrabadaWeb2Client.CrabadaWeb2Client import CrabadaWeb2Client
>   File "/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 223, in <module>
>     response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
> NameError: name 'params' is not defined
> ```

ur params object is not defined, should be `actualParams`

**Comment by EugeneTeu** [comment]
> 



> @kraussian @EugeneTeu
> 
> I have added the headers but I am getting this error after running the code to close mines. I am probably doing something wrong when adding those headers.
> 
> ```
>   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/bin/mining/closeMines.py", line 13, in <module>
>     from src.bot.mining.closeMines import closeMines
>   File "/src/bot/mining/closeMines.py", line 9, in <module>
>     from src.common.clients import makeCrabadaWeb3Client
>   File "/src/common/clients.py", line 8, in <module>
>     from src.libs.CrabadaWeb2Client.CrabadaWeb2Client import CrabadaWeb2Client
>   File "/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 223, in <module>
>     response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
> NameError: name 'params' is not defined
> ```

ur params object is not defined, should be `actualParams`

**Comment by flazewang** [comment]
> > 
> 
> > @kraussian @EugeneTeu
> > I have added the headers but I am getting this error after running the code to close mines. I am probably doing something wrong when adding those headers.
> > ```
> >   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/bin/mining/closeMines.py", line 13, in <module>
> >     from src.bot.mining.closeMines import closeMines
> >   File "/src/bot/mining/closeMines.py", line 9, in <module>
> >     from src.common.clients import makeCrabadaWeb3Client
> >   File "/src/common/clients.py", line 8, in <module>
> >     from src.libs.CrabadaWeb2Client.CrabadaWeb2Client import CrabadaWeb2Client
> >   File "/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 223, in <module>
> >     response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
> > NameError: name 'params' is not defined
> > ```
> 
> ur params object is not defined, should be `actualParams`



> > 
> 
> > @kraussian @EugeneTeu
> > I have added the headers but I am getting this error after running the code to close mines. I am probably doing something wrong when adding those headers.
> > ```
> >   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/bin/mining/closeMines.py", line 13, in <module>
> >     from src.bot.mining.closeMines import closeMines
> >   File "/src/bot/mining/closeMines.py", line 9, in <module>
> >     from src.common.clients import makeCrabadaWeb3Client
> >   File "/src/common/clients.py", line 8, in <module>
> >     from src.libs.CrabadaWeb2Client.CrabadaWeb2Client import CrabadaWeb2Client
> >   File "/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 223, in <module>
> >     response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
> > NameError: name 'params' is not defined
> > ```
> 
> ur params object is not defined, should be `actualParams`

I have managed to get it running, however, it is saying no mines to reinforce nor mines to close when they are there on the site, any ideas? Thank you very much.

**Comment by flazewang** [comment]
> > 
> 
> > @kraussian @EugeneTeu
> > I have added the headers but I am getting this error after running the code to close mines. I am probably doing something wrong when adding those headers.
> > ```
> >   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/bin/mining/closeMines.py", line 13, in <module>
> >     from src.bot.mining.closeMines import closeMines
> >   File "/src/bot/mining/closeMines.py", line 9, in <module>
> >     from src.common.clients import makeCrabadaWeb3Client
> >   File "/src/common/clients.py", line 8, in <module>
> >     from src.libs.CrabadaWeb2Client.CrabadaWeb2Client import CrabadaWeb2Client
> >   File "/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 223, in <module>
> >     response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
> > NameError: name 'params' is not defined
> > ```
> 
> ur params object is not defined, should be `actualParams`



> > 
> 
> > @kraussian @EugeneTeu
> > I have added the headers but I am getting this error after running the code to close mines. I am probably doing something wrong when adding those headers.
> > ```
> >   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/bin/mining/closeMines.py", line 13, in <module>
> >     from src.bot.mining.closeMines import closeMines
> >   File "/src/bot/mining/closeMines.py", line 9, in <module>
> >     from src.common.clients import makeCrabadaWeb3Client
> >   File "/src/common/clients.py", line 8, in <module>
> >     from src.libs.CrabadaWeb2Client.CrabadaWeb2Client import CrabadaWeb2Client
> >   File "/src/libs/CrabadaWeb2Client/CrabadaWeb2Client.py", line 223, in <module>
> >     response = requests.get('https://idle-api.crabada.com/public/idle/mines', headers=headers, params=params)
> > NameError: name 'params' is not defined
> > ```
> 
> ur params object is not defined, should be `actualParams`

I have managed to get it running, however, it is saying no mines to reinforce nor mines to close when they are there on the site, any ideas? Thank you very much.

**Comment by coccoinomane** [comment]
Thank you guys for reporting the issue, I have just merged @EugeneTeu's fix (https://github.com/coccoinomane/crabada.py/pull/65)

Let me know if it works for you!

PS: @flazewang the *No mines to reinforce error* usually comes from some typo in the team configuration in _.env_, could you please  double check?

**Comment by kraussian** [comment]
@coccoinomane I've realized that the "No mines to reinforce" error is due to Crabada lowering their API search limit to 100, but the program is requesting for limit 200 by default. This needs to be lowered to 100 or less.

**Comment by coccoinomane** [comment]
> @coccoinomane I've realized that the "No suitable reinforcements" error is due to Crabada lowering their API search limit to 100, but the program is requesting for limit 200 by default. This needs to be lowered to 100 or less.

@kraussian @flazewang 

Cool, then we killed two birds with one stone ;-)

Could you please check whether `master` works for you now?

Cheers,
Cocco

**Comment by flazewang** [comment]
Okay so, for looting, I am unable to close loots, as I have several I kept on Settle by purpose of testing this. .env config is exactly the same as before the change in API so there shouldn't be any issues. Maybe the way loots are being handled changed.

"src.common.logger - INFO - No loots to close for user"

Also for mining I am getting the same results. with Limit in strat changed to 100.

**Comment by flazewang** [comment]
Okay so, for looting, I am unable to close loots, as I have several I kept on Settle by purpose of testing this. .env config is exactly the same as before the change in API so there shouldn't be any issues. Maybe the way loots are being handled changed.

"src.common.logger - INFO - No loots to close for user"

Also for mining I am getting the same results. with Limit in strat changed to 100.

**Comment by flazewang** [comment]
Deleted my previous comment, works fine now. There was some connection issue on my part.

**Comment by flazewang** [comment]
Deleted my previous comment, works fine now. There was some connection issue on my part.

**Comment by coccoinomane** [comment]
Great, thanks for letting me know!

Closing the issue 🤞

Cheers,
Cocco
