### ISSUE TITLE
Weird reinforcements

### ISSUE THREAD

**Issue by Mrooie** [coccoinomane/crabada.py#70]
Hi!
I found a weird reinforcement issue. Here is my env:

> USER_1_REINFORCEMENT_MAX_PRICE="25"
> USER_1_REINFORCEMENT_MAX_GAS="90"
> USER_1_MINE_MAX_GAS="95"
> USER_1_CLOSE_MINE_MAX_GAS="95"
>
> USER_1_TEAM_1_REINFORCE_STRATEGY="HighestMpFromInventory, HighestBpFromInventory, NoReinforce"
> USER_1_TEAM_1_TASK="mine"
> USER_1_TEAM_1_REINFORCEMENT_TO_PICK="1"
>
> USER_1_TEAM_1_REINFORCE_STRATEGY="HighestBpFromInventory, HighestMpFromInventory, NoReinforce"
> USER_1_TEAM_1_TASK="mine"
> USER_1_TEAM_1_REINFORCEMENT_TO_PICK="1"

So it shouldn't reinforce if it doesn't find crabs in my inventory, right? But it still rents out really cheap crabs from the tavern. 🤔

**Comment by Mrooie** [comment]
I've tried to change MAX_PRICE to 1.
Logger printed:
>src.common.logger - INFO - Strategy 'HighestBp' could not find a suitable reinforcement for team

So my guess is, that it still uses HighestBP tavern strategy?

**Comment by coccoinomane** [comment]
Hi @Mrooie ,

Thanks for reporting the issue and for the extra debug you did!

It seems that the bot fails to read your `USER_1_TEAM_1_REINFORCE_STRATEGY` setting from _.env_ and falls back to the default strategy, which is `HighestBP`.

Could you please perform the following checks:

1. Run `python3 -m src.tests.testConfig` and verify whether the value of `reinforceStrategies` checks out (please **do not paste the output here as it will contain your key!**.)
2. Check the syntax of your _.env_ file. From the snippet you posted, I can see duplicate config values, maybe there are other potential issues?

Cheers,
Cocco

**Comment by coccoinomane** [comment]
Great, thank you for letting me know @Mrooie !

Cheers,
Cocco
