### ISSUE TITLE
Suggestion mine reinforce

### ISSUE THREAD

**Issue by loayei** [coccoinomane/crabada.py#82]
This is not an issue but a mere suggestion to implement. 

Get the difference between attacker bp and looter bp if difference is below 6 bp for example reinforce with a legendary.
Can be an option on the .env as 0 or 1.

**Comment by nikohd12** [comment]
Hey bro @loayei ,

you can make this as a reinforce strategy. You just need to define a parameter. 

Maybe a strategy that reinforces 238+ BP if certain conditions are met.

**Comment by loayei** [comment]
Will try it out and then do a pull request.. 👯
