### ISSUE TITLE
HighestMp Reinforce Strategy not working

### ISSUE THREAD

**Issue by nikojaro** [coccoinomane/crabada.py#9]
Hello Cocco!

The .env option **USER_1_TEAM_1_REINFORCE_STRATEGY="HighestMp"** is not working, it still reinforces HighestBp.

In order for this strategy to work, I am currently replacing ReinforceStrategy.py to supply "HighestMp" as a strategy name.

`  # Create the strategy object and use it to get the crab to borrow
    strategy: ReinforceStrategy = makeReinforceStrategy("HighestMp", mine, maxPrice)
    return strategy.getCrab(lootingOrMining)`

Additionally **(for looting)**, reinforceAttack is not working. Automating reinforce on looting and settling is a big help already, we can just find match manually.

I have tried the fix suggested here https://github.com/coccoinomane/crabada.py/commit/269275c572bfbb21ba71dea1d6c2e3edf6ae95be#r68697734 but it can't find any crabs despite high availability of Bulks (HighestBp)

**Comment by coccoinomane** [comment]
Hi @nikojaro , thank you for your feedback!

I did not manage to reproduce your issue with the reinforce strategy, it all works fine for me.

I have pushed a new test, could you please try to run it:

```
python3 -m src.tests.strategies.reinforce.testMakeReinforceStrategy
```

The test will print the strategy that will be used to reinforce & print the crab that the strategy will choose.
I have run the test on my side and it correctly selects a high MP crab when `USER_1_TEAM_1_REINFORCE_STRATEGY="HighestMp"`, here's a screenshot.

![Markup 2022-03-15 at 14 59 56](https://user-images.githubusercontent.com/3920436/158400666-bcdc99bf-81c8-4a04-bb44-5c321846cd59.png)

**Comment by coccoinomane** [comment]
PS: As for `reinforceAttack `, there was indeed a bug and I fixed it in the last commit.

Could you please try `reinforceAttack` again and open a new issue (separate from this one) if you still have problems?

Cheers,
Cocco

**Comment by nikojaro** [comment]
> Hi @nikojaro , thank you for your feedback!
> 
> I did not manage to reproduce your issue with the reinforce strategy, it all works fine for me.
> 
> I have pushed a new test, could you please try to run it:
> 
> ```
> python3 -m src.tests.strategies.reinforce.testMakeReinforceStrategy
> ```
> 
> The test will print the strategy that will be used to reinforce & print the crab that the strategy will choose. I have run the test on my side and it correctly selects a high MP crab when `USER_1_TEAM_1_REINFORCE_STRATEGY="HighestMp"`, here's a screenshot.
> 
> ![Markup 2022-03-15 at 14 59 56](https://user-images.githubusercontent.com/3920436/158400666-bcdc99bf-81c8-4a04-bb44-5c321846cd59.png)

Hi Cocco,

Thanks, I’ll try it out. I’ll clear pycache before running. Do you think that should be included in the README section?

**Comment by nikojaro** [comment]
> PS: As for `reinforceAttack `, there was indeed a bug and I fixed it in the last commit.
> 
> Could you please try `reinforceAttack` again and open a new issue (separate from this one) if you still have problems?
> 
> Cheers, Cocco

Hi Cocco,

I am getting the following error for reinforceAttack

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/crabada-niko/bin/looting/reinforceAttack.py", line 28, in                                                                                                                                                                                                                                              <module>
    nReinforced = reinforceAttack(userAddress)
  File "/home/ec2-user/crabada-niko/src/bot/looting/reinforceAttack.py", line 40                                                                                                                                                                                                                                             , in reinforceAttack
    strategyName = user.getTeamConfig(mine["team_id"]).get("reinforceStrategyNam                                                                                                                                                                                                                                             e")
AttributeError: 'NoneType' object has no attribute 'get'
`

Tried clearing python cache but I'm still getting the errors.
**find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf**

**Comment by nikojaro** [comment]
> Hi @nikojaro , thank you for your feedback!
> 
> I did not manage to reproduce your issue with the reinforce strategy, it all works fine for me.
> 
> I have pushed a new test, could you please try to run it:
> 
> ```
> python3 -m src.tests.strategies.reinforce.testMakeReinforceStrategy
> ```
> 
> The test will print the strategy that will be used to reinforce & print the crab that the strategy will choose. I have run the test on my side and it correctly selects a high MP crab when `USER_1_TEAM_1_REINFORCE_STRATEGY="HighestMp"`, here's a screenshot.
> 
> ![Markup 2022-03-15 at 14 59 56](https://user-images.githubusercontent.com/3920436/158400666-bcdc99bf-81c8-4a04-bb44-5c321846cd59.png)

Working correctly now. 

```
src.common.logger - INFO - Borrowing crab 9230 for mine 2440900 at 20 TUS... [strategy=HighestMp, BP=220, MP=82]
src.common.txLogger - INFO - 0xd125d79d182af35c0c8099fcc1b3c99cd121f9e7556ebbad0485802e0f82b5c6
src.common.logger - INFO - Mine 2440900 reinforced correctly
src.common.logger - INFO - Borrowing crab 9230 for mine 2440894 at 20 TUS... [strategy=HighestMp, BP=220, MP=82]
src.common.txLogger - INFO - 0xd911b2ce591f0ef328f1af667b1ca4ee60f3a5fa73cc2b09a4dd95f6bbbdb97d
src.common.logger - ERROR - Error reinforcing mine 2440894
src.common.logger - INFO - Borrowing crab 9230 for mine 2440848 at 20 TUS... [strategy=HighestMp, BP=220, MP=82]
src.common.txLogger - INFO - 0x40b497232a8e68da31903d11947f756efef4bd04ecfa442fc3b4c23eb3702258
src.common.logger - ERROR - Error reinforcing mine 2440848
```

P.S I have also tested reinforceDelay yesterday and it was working stable for about 20 hours.

**Comment by nikojaro** [comment]
Closing this issue now.
