### ISSUE TITLE
Increasing the MP while reinforcing with minimum MP setting & maximum Price setting.

### ISSUE THREAD

**Issue by CBSInvest** [coccoinomane/crabada.py#92]
Hi,
just witnessed when trying to use the automate reinforcement that what ever u use for the REINFORCE_STRATEGY="HighestMp" and the REINFORCEMENT_TO_PICK="90" up to 100 caused by the large number of crabs in the tavern u only get 66 MP as a reinforcement which makes no real sense so if we could use a minimum MP in the Bot combined with a maximum REINFORCEMENT_MAX_PRICE="15", that we get lets say a minimum of 78 MP for the best price available under 15, so u dont get a fill with 66 MP for example. 

Can this be implemented in the ENV as a fix setting it would make a lot of sense and i guess this will be also the issue on the looting side but even more dramatic if the bot uses a very low one that ur miner opponent even get a higher BP and automatically wins!

Thanks to all contributors !

**Comment by coccoinomane** [comment]
Hi,

It makes no sense to set `REINFORCEMENT_TO_PICK` to such high value.

Please read the [relevant README section](https://github.com/coccoinomane/crabada.py#--avoid-the-competition) for more details.

Cheers,
Cocco

**Comment by CBSInvest** [comment]
Hi Cocco, 

i am aware of the README section just used different numbers throughout the teams to get maybe a better result with the high MR number cause the result is the same that u get pretty low MP with the HighestMp Order 

Maybe because of the current situation but a min MP to choose at least a certain level could help specially with looting where the high BP is important to have a min Level in place or maybe i am the only one seeing this issue following the results !

Maybe the community is having an idea !

All the best
Claus
